### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by dna75** [cactusss/nl.onzewifi.DeebotT9#8]
I installed  the Homey Pro app but when I click on SQL the config remains blank. A restart / reinstall doesn't have any effect.

**Comment by Boechie** [comment]
@dna75 I think this issue is about insights2sql and therefore in the wrong place. I think this issue in the right place alrady describes you issue, right? https://github.com/cactusss/nl.onzewifi.insights2sql/issues/3
Consider closing this issue as not planned.
